<a href="https://colab.research.google.com/github/rprakashiyer/Python/blob/main/numpy_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [100]:
import numpy as np

### gdown is the command to download file directly from google drive

In [82]:
!gdown 1kXqcJo4YzmwF1G2BPoA17CI49TZVHANF

Downloading...
From: https://drive.google.com/uc?id=1kXqcJo4YzmwF1G2BPoA17CI49TZVHANF
To: /content/fitness.txt
100% 3.14k/3.14k [00:00<00:00, 8.22MB/s]


In [5]:
a = np.array([4,6,3,1,0,10,25,21,22,9,5,2])
a

array([ 4,  6,  3,  1,  0, 10, 25, 21, 22,  9,  5,  2])

### normal sort function

In [6]:
a.sort()

In [7]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  9, 10, 21, 22, 25])

In [8]:
a = np.array([4,6,3,1,0,10,25,21,22,9,5,2])
a

array([ 4,  6,  3,  1,  0, 10, 25, 21, 22,  9,  5,  2])

### argsort is one function which provides us with the indexes of the sorted values

In [9]:
np.argsort(a)

array([ 4,  3, 11,  2,  0, 10,  1,  9,  5,  7,  8,  6])

### argmax gives us the index of the maximum value in the array

In [10]:
np.argmax(a)

6

### argmin gives us the index of the minimum value in the array

In [11]:
np.argmin(a)

4

### while min & max only gives minimum and maximum values in the array

In [14]:
np.min(a)

0

In [15]:
np.max(a)

25

### A 2D matrix

In [19]:
b=np.array([[20,2,34],[13,1,26],[12,7,95]])
b

array([[20,  2, 34],
       [13,  1, 26],
       [12,  7, 95]])

### Default axis for sort is horizontal axis, i.e axis = 1
###For Verticle sort,   axis = 0

In [18]:
np.sort(b)

array([[ 2, 20, 34],
       [ 1, 13, 26],
       [ 7, 12, 95]])

In [27]:
b=np.array([[20,2,34],[13,1,26],[12,7,95]])
b

array([[20,  2, 34],
       [13,  1, 26],
       [12,  7, 95]])

In [28]:
np.sort(b,axis=0)

array([[12,  1, 26],
       [13,  2, 34],
       [20,  7, 95]])

In [29]:
np.argsort(b,axis=0)

array([[2, 1, 1],
       [1, 0, 0],
       [0, 2, 2]])

In [30]:
b

array([[20,  2, 34],
       [13,  1, 26],
       [12,  7, 95]])

In [25]:
b = np.sort(b,axis=0)

In [26]:
b

array([[12,  1, 26],
       [13,  2, 34],
       [20,  7, 95]])

In [83]:
fit_data = np.loadtxt('/content/fitness.txt',dtype = str)

# date,step_count,mood,calories_burned,
# hours_of_sleep,bool_of_active,weight_kg

In [146]:
fit_data

array([['06-10-2017', '5464', 'Neutral', '181', '5', 'Inactive', '66'],
       ['07-10-2017', '6041', 'Sad', '197', '8', 'Inactive', '66'],
       ['08-10-2017', '25', 'Sad', '0', '5', 'Inactive', '66'],
       ['09-10-2017', '5461', 'Sad', '174', '4', 'Inactive', '66'],
       ['10-10-2017', '6915', 'Neutral', '223', '5', 'Active', '66'],
       ['11-10-2017', '4545', 'Sad', '149', '6', 'Inactive', '66'],
       ['12-10-2017', '4340', 'Sad', '140', '6', 'Inactive', '66'],
       ['13-10-2017', '1230', 'Sad', '38', '7', 'Inactive', '66'],
       ['14-10-2017', '61', 'Sad', '1', '5', 'Inactive', '66'],
       ['15-10-2017', '1258', 'Sad', '40', '6', 'Inactive', '65'],
       ['16-10-2017', '3148', 'Sad', '101', '8', 'Inactive', '65'],
       ['17-10-2017', '4687', 'Sad', '152', '5', 'Inactive', '65'],
       ['18-10-2017', '4732', 'Happy', '150', '6', 'Active', '65'],
       ['19-10-2017', '3519', 'Sad', '113', '7', 'Inactive', '65'],
       ['20-10-2017', '1580', 'Sad', '49', '5', 'Ina

In [147]:
fit_data.shape

(96, 7)

In [148]:
fit_data[0]

array(['06-10-2017', '5464', 'Neutral', '181', '5', 'Inactive', '66'],
      dtype='<U10')

In [149]:
fit_data[:5,:]

array([['06-10-2017', '5464', 'Neutral', '181', '5', 'Inactive', '66'],
       ['07-10-2017', '6041', 'Sad', '197', '8', 'Inactive', '66'],
       ['08-10-2017', '25', 'Sad', '0', '5', 'Inactive', '66'],
       ['09-10-2017', '5461', 'Sad', '174', '4', 'Inactive', '66'],
       ['10-10-2017', '6915', 'Neutral', '223', '5', 'Active', '66']],
      dtype='<U10')

In [37]:
data1=np.array([[1,2,3]])
print(data1)

[[1 2 3]]


In [38]:
data1.T

array([[1],
       [2],
       [3]])

### Here after transposing, the array of (3,1) is unpacked into different variables a,b & c

In [39]:
a,b,c = data1.T

In [40]:
a

array([1])

In [41]:
b

array([2])

In [42]:
c

array([3])

In [150]:
fit_data.T

array([['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
        '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
        '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
        '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
        '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
        '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
        '30-10-2017', '31-10-2017', '01-11-2017', '02-11-2017',
        '03-11-2017', '04-11-2017', '05-11-2017', '06-11-2017',
        '07-11-2017', '08-11-2017', '09-11-2017', '10-11-2017',
        '11-11-2017', '12-11-2017', '13-11-2017', '14-11-2017',
        '15-11-2017', '16-11-2017', '17-11-2017', '18-11-2017',
        '19-11-2017', '20-11-2017', '21-11-2017', '22-11-2017',
        '23-11-2017', '24-11-2017', '25-11-2017', '26-11-2017',
        '27-11-2017', '28-11-2017', '29-11-2017', '30-11-2017',
        '01-12-2017', '02-12-2017', '03-12-2017', '04-12-2017',
        '05-12-2017', '06-12-2017', '07-

In [151]:
date,step_count,mood,calories_burned,hours_of_sleep,bool_of_active,weight_kg = fit_data.T

In [152]:
date

array(['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
       '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
       '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
       '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
       '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
       '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
       '30-10-2017', '31-10-2017', '01-11-2017', '02-11-2017',
       '03-11-2017', '04-11-2017', '05-11-2017', '06-11-2017',
       '07-11-2017', '08-11-2017', '09-11-2017', '10-11-2017',
       '11-11-2017', '12-11-2017', '13-11-2017', '14-11-2017',
       '15-11-2017', '16-11-2017', '17-11-2017', '18-11-2017',
       '19-11-2017', '20-11-2017', '21-11-2017', '22-11-2017',
       '23-11-2017', '24-11-2017', '25-11-2017', '26-11-2017',
       '27-11-2017', '28-11-2017', '29-11-2017', '30-11-2017',
       '01-12-2017', '02-12-2017', '03-12-2017', '04-12-2017',
       '05-12-2017', '06-12-2017', '07-12-2017', '08-12

In [153]:
date[69]

'14-12-2017'

In [45]:
date.shape

(96,)

In [154]:
step_count

array(['5464', '6041', '25', '5461', '6915', '4545', '4340', '1230', '61',
       '1258', '3148', '4687', '4732', '3519', '1580', '2822', '181',
       '3158', '4383', '3881', '4037', '202', '292', '330', '2209',
       '4550', '4435', '4779', '1831', '2255', '539', '5464', '6041',
       '4068', '4683', '4033', '6314', '614', '3149', '4005', '4880',
       '4136', '705', '570', '269', '4275', '5999', '4421', '6930',
       '5195', '546', '493', '995', '1163', '6676', '3608', '774', '1421',
       '4064', '2725', '5934', '1867', '3721', '2374', '2909', '1648',
       '799', '7102', '3941', '7422', '437', '1231', '1696', '4921',
       '221', '6500', '3575', '4061', '651', '753', '518', '5537', '4108',
       '5376', '3066', '177', '36', '299', '1447', '2599', '702', '133',
       '153', '500', '2127', '2203'], dtype='<U10')

In [155]:
step_count.dtype

dtype('<U10')

In [156]:
step_count = np.array(step_count,dtype=int)

In [157]:
step_count.dtype

dtype('int64')

In [158]:
step_count

array([5464, 6041,   25, 5461, 6915, 4545, 4340, 1230,   61, 1258, 3148,
       4687, 4732, 3519, 1580, 2822,  181, 3158, 4383, 3881, 4037,  202,
        292,  330, 2209, 4550, 4435, 4779, 1831, 2255,  539, 5464, 6041,
       4068, 4683, 4033, 6314,  614, 3149, 4005, 4880, 4136,  705,  570,
        269, 4275, 5999, 4421, 6930, 5195,  546,  493,  995, 1163, 6676,
       3608,  774, 1421, 4064, 2725, 5934, 1867, 3721, 2374, 2909, 1648,
        799, 7102, 3941, 7422,  437, 1231, 1696, 4921,  221, 6500, 3575,
       4061,  651,  753,  518, 5537, 4108, 5376, 3066,  177,   36,  299,
       1447, 2599,  702,  133,  153,  500, 2127, 2203])

In [113]:
step_count.shape

(96,)

In [114]:
np.max(step_count)

7422

In [159]:
weight_kg = np.array(weight_kg,dtype=int)
calories_burned = np.array(calories_burned,dtype=int)

In [116]:
weight_kg.dtype

dtype('int64')

In [160]:
calories_burned.dtype

dtype('int64')

In [117]:
np.max(weight_kg)

66

In [118]:
weight_kg

array([66, 66, 66, 66, 66, 66, 66, 66, 66, 65, 65, 65, 65, 65, 65, 65, 65,
       65, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64,
       64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64,
       64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64,
       64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64,
       64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64])

In [119]:
np.unique(weight_kg,return_counts=True)

(array([64, 65, 66]), array([78,  9,  9]))

In [74]:
mood

array(['200', '100', '100', '100', '200', '100', '100', '100', '100',
       '100', '100', '100', '300', '100', '100', '100', '100', '200',
       '200', '200', '200', '200', '200', '300', '200', '300', '300',
       '300', '300', '300', '300', '300', '200', '300', '300', '300',
       '300', '300', '300', '300', '300', '300', '300', '200', '300',
       '300', '300', '300', '300', '300', '300', '300', '300', '200',
       '100', '300', '300', '300', '300', '300', '300', '300', '100',
       '200', '200', '100', '100', '200', '200', '300', '200', '200',
       '100', '200', '100', '200', '200', '100', '100', '100', '100',
       '300', '200', '300', '200', '100', '100', '100', '200', '200',
       '100', '100', '300', '200', '200', '300'], dtype='<U10')

In [75]:
np.unique(mood,return_counts=True)

(array(['100', '200', '300'], dtype='<U10'), array([29, 27, 40]))

In [50]:
mood.shape

(96,)

In [51]:
np.unique(mood)

array(['100', '200', '300'], dtype='<U10')

In [87]:
mood[mood=='100'] = 'Sad'
mood[mood=='200'] = 'Neutral'
mood[mood=='300'] = 'Happy'

In [57]:
mood

array(['Neutral', 'Sad', 'Sad', 'Sad', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Sad', 'Sad', 'Sad', 'Sad', 'Happy', 'Sad', 'Sad', 'Sad', 'Sad',
       'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral',
       'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Neutral',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Neutral', 'Sad', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Sad', 'Neutral', 'Neutral',
       'Sad', 'Sad', 'Neutral', 'Neutral', 'Happy', 'Neutral', 'Neutral',
       'Sad', 'Neutral', 'Sad', 'Neutral', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Sad', 'Happy', 'Neutral', 'Happy', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Neutral', 'Neutral', 'Sad', 'Sad', 'Happy', 'Neutral', 'Neutral',
       'Happy'], dtype='<U10')

In [95]:
np.unique(mood,return_counts=True)

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'), array([40, 27, 29]))

In [78]:
bool_of_active


array(['0', '0', '0', '0', '500', '0', '0', '0', '0', '0', '0', '0',
       '500', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '500', '0', '0', '0', '0', '500', '0', '0', '0', '0', '0', '500',
       '500', '500', '500', '500', '500', '500', '500', '500', '0', '0',
       '0', '0', '0', '0', '500', '500', '500', '500', '500', '500',
       '500', '500', '500', '500', '500', '500', '0', '500', '500', '0',
       '500', '500', '500', '500', '500', '0', '500', '500', '500', '500',
       '0', '0', '0', '0', '500', '500', '500', '500', '0', '0', '0', '0',
       '0', '0', '0', '0', '500', '0', '500'], dtype='<U10')

In [88]:
bool_of_active[bool_of_active == '0'] = 'Inactive'
bool_of_active[bool_of_active == '500'] = 'Active'

In [94]:
bool_of_active


array(['Inactive', 'Inactive', 'Inactive', 'Inactive', 'Active',
       'Inactive', 'Inactive', 'Inactive', 'Inactive', 'Inactive',
       'Inactive', 'Inactive', 'Active', 'Inactive', 'Inactive',
       'Inactive', 'Inactive', 'Inactive', 'Inactive', 'Inactive',
       'Inactive', 'Inactive', 'Inactive', 'Inactive', 'Inactive',
       'Active', 'Inactive', 'Inactive', 'Inactive', 'Inactive', 'Active',
       'Inactive', 'Inactive', 'Inactive', 'Inactive', 'Inactive',
       'Active', 'Active', 'Active', 'Active', 'Active', 'Active',
       'Active', 'Active', 'Active', 'Inactive', 'Inactive', 'Inactive',
       'Inactive', 'Inactive', 'Inactive', 'Active', 'Active', 'Active',
       'Active', 'Active', 'Active', 'Active', 'Active', 'Active',
       'Active', 'Active', 'Active', 'Inactive', 'Active', 'Active',
       'Inactive', 'Active', 'Active', 'Active', 'Active', 'Active',
       'Inactive', 'Active', 'Active', 'Active', 'Active', 'Inactive',
       'Inactive', 'Inactive', 'Inacti

In [120]:
fit_data

array([['06-10-2017', '5464', 'Neutral', '181', '5', 'Inactive', '66'],
       ['07-10-2017', '6041', 'Sad', '197', '8', 'Inactive', '66'],
       ['08-10-2017', '25', 'Sad', '0', '5', 'Inactive', '66'],
       ['09-10-2017', '5461', 'Sad', '174', '4', 'Inactive', '66'],
       ['10-10-2017', '6915', 'Neutral', '223', '5', 'Active', '66'],
       ['11-10-2017', '4545', 'Sad', '149', '6', 'Inactive', '66'],
       ['12-10-2017', '4340', 'Sad', '140', '6', 'Inactive', '66'],
       ['13-10-2017', '1230', 'Sad', '38', '7', 'Inactive', '66'],
       ['14-10-2017', '61', 'Sad', '1', '5', 'Inactive', '66'],
       ['15-10-2017', '1258', 'Sad', '40', '6', 'Inactive', '65'],
       ['16-10-2017', '3148', 'Sad', '101', '8', 'Inactive', '65'],
       ['17-10-2017', '4687', 'Sad', '152', '5', 'Inactive', '65'],
       ['18-10-2017', '4732', 'Happy', '150', '6', 'Active', '65'],
       ['19-10-2017', '3519', 'Sad', '113', '7', 'Inactive', '65'],
       ['20-10-2017', '1580', 'Sad', '49', '5', 'Ina

In [121]:
np.argmax(step_count)

69

In [122]:
date[69]

'14-12-2017'

### Date on which maximum steps were taken

In [123]:
date[np.argmax(step_count)]

'14-12-2017'

### Mood when maximum steps were taken

In [124]:
mood[np.argmax(step_count)]

'Happy'

### Calories burnt when maximum steps were taken

In [161]:
calories_burned

array([181, 197,   0, 174, 223, 149, 140,  38,   1,  40, 101, 152, 150,
       113,  49,  86,   6,  99, 143, 125, 129,   6,   9,  10,  72, 150,
       141, 156,  57,  72,  17, 181, 197, 131, 154, 137, 193,  19, 101,
       139, 164, 137,  22,  17,   9, 145, 192, 146, 234, 167,  16,  17,
        32,  35, 220, 116,  23,  44, 131,  86, 194,  60, 121,  76,  93,
        53,  25, 227, 125, 243,  14,  39,  55, 158,   7, 213, 116, 129,
        21,  28,  16, 180, 138, 176,  99,   5,   1,  10,  47,  84,  23,
         4,   0,   0,   0,   0])

In [162]:
calories_burned[np.argmax(step_count)]


243

In [126]:
np.mean(step_count)

2935.9375

In [139]:
hours_of_sleep=np.array(hours_of_sleep,dtype="int")
hours_of_sleep[:5]

array([5, 8, 5, 4, 5])

In [140]:
fit_data

array([['06-10-2017', '5464', 'Neutral', '181', '5', 'Inactive', '66'],
       ['07-10-2017', '6041', 'Sad', '197', '8', 'Inactive', '66'],
       ['08-10-2017', '25', 'Sad', '0', '5', 'Inactive', '66'],
       ['09-10-2017', '5461', 'Sad', '174', '4', 'Inactive', '66'],
       ['10-10-2017', '6915', 'Neutral', '223', '5', 'Active', '66'],
       ['11-10-2017', '4545', 'Sad', '149', '6', 'Inactive', '66'],
       ['12-10-2017', '4340', 'Sad', '140', '6', 'Inactive', '66'],
       ['13-10-2017', '1230', 'Sad', '38', '7', 'Inactive', '66'],
       ['14-10-2017', '61', 'Sad', '1', '5', 'Inactive', '66'],
       ['15-10-2017', '1258', 'Sad', '40', '6', 'Inactive', '65'],
       ['16-10-2017', '3148', 'Sad', '101', '8', 'Inactive', '65'],
       ['17-10-2017', '4687', 'Sad', '152', '5', 'Inactive', '65'],
       ['18-10-2017', '4732', 'Happy', '150', '6', 'Active', '65'],
       ['19-10-2017', '3519', 'Sad', '113', '7', 'Inactive', '65'],
       ['20-10-2017', '1580', 'Sad', '49', '5', 'Ina

In [132]:
step_count

array([5464, 6041,   25, 5461, 6915, 4545, 4340, 1230,   61, 1258, 3148,
       4687, 4732, 3519, 1580, 2822,  181, 3158, 4383, 3881, 4037,  202,
        292,  330, 2209, 4550, 4435, 4779, 1831, 2255,  539, 5464, 6041,
       4068, 4683, 4033, 6314,  614, 3149, 4005, 4880, 4136,  705,  570,
        269, 4275, 5999, 4421, 6930, 5195,  546,  493,  995, 1163, 6676,
       3608,  774, 1421, 4064, 2725, 5934, 1867, 3721, 2374, 2909, 1648,
        799, 7102, 3941, 7422,  437, 1231, 1696, 4921,  221, 6500, 3575,
       4061,  651,  753,  518, 5537, 4108, 5376, 3066,  177,   36,  299,
       1447, 2599,  702,  133,  153,  500, 2127, 2203])

### Frequency of mood variable when the step count is greater than 4500

In [164]:
mood[step_count>4500]

array(['Neutral', 'Sad', 'Sad', 'Neutral', 'Sad', 'Sad', 'Happy', 'Happy',
       'Happy', 'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Sad', 'Happy', 'Neutral', 'Happy', 'Neutral',
       'Neutral', 'Happy', 'Happy'], dtype='<U10')

In [165]:
np.unique(mood[step_count>4500],return_counts=True)

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'), array([14,  6,  5]))

In [167]:
hours_of_sleep = np.array(hours_of_sleep,dtype=int)

In [169]:
np.mean(hours_of_sleep)

5.21875

In [170]:
arr = np.array([-3,4,27,34,-2, 0, -45,-11,4, 0 ])
arr

array([ -3,   4,  27,  34,  -2,   0, -45, -11,   4,   0])

In [171]:
arr[arr>0] = 1

In [172]:
arr

array([ -3,   1,   1,   1,  -2,   0, -45, -11,   1,   0])

In [173]:
arr[arr<0] = -1

In [174]:
arr

array([-1,  1,  1,  1, -1,  0, -1, -1,  1,  0])

In [175]:
arr = np.array([-3,4,27,34,-2, 0, -45,-11,4, 0 ])
arr

array([ -3,   4,  27,  34,  -2,   0, -45, -11,   4,   0])

In [176]:
arr1 = np.where(arr > 0,1,-1)

In [177]:
arr1

array([-1,  1,  1,  1, -1, -1, -1, -1,  1, -1])

In [178]:
a=np.arange(1,10).reshape((3,3))
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [179]:
b=np.arange(2,11).reshape((3,3))
b

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

### np.matmul & np.dot are used for matrix multiplication

In [180]:
np.matmul(a,b)

array([[ 36,  42,  48],
       [ 81,  96, 111],
       [126, 150, 174]])

In [181]:
np.matmul(b,a)

array([[ 42,  51,  60],
       [ 78,  96, 114],
       [114, 141, 168]])

In [182]:
a@b

array([[ 36,  42,  48],
       [ 81,  96, 111],
       [126, 150, 174]])

In [183]:
b@a

array([[ 42,  51,  60],
       [ 78,  96, 114],
       [114, 141, 168]])

In [184]:
np.dot(a,b)

array([[ 36,  42,  48],
       [ 81,  96, 111],
       [126, 150, 174]])

### There is a slight difference between np.dot() & np.matmul() is that, np.dot() would work for scalar multiplication, but np.matmul() wouldnt

In [185]:
np.dot(4,5)

20

In [186]:
np.matmul(5,6)

ValueError: ignored

In [187]:
np.tile(a,(2,2))

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9],
       [1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])