In [1]:
import numpy as np




#Fancy Indexing (Masking)**

In [3]:
e = np.arange(12).reshape(3,4)
e

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [7]:
e.ndim

2

In [18]:
mask = e<6
mask

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False]])

In [22]:
mask.ndim

2

In [5]:
e[e<6]

array([0, 1, 2, 3, 4, 5])

In [6]:
e[e<6].ndim

1

In [8]:
type(e)

numpy.ndarray

In [15]:
x = (e%2==0)
x

array([[ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False]])

In [13]:
type(x)

numpy.ndarray

In [16]:
y = (e%5==0)
y

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False]])

#Interesting

In [17]:
x == y

array([[ True,  True, False,  True],
       [False, False, False,  True],
       [False,  True,  True,  True]])

In [23]:
e

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [25]:
e.shape

(3, 4)

In [26]:
x,y = e.shape

In [27]:
x

3

In [28]:
y

4

In [36]:
mask = ((e%3 == 0)&(e%2==0))
mask

array([[ True, False, False, False],
       [False, False,  True, False],
       [False, False, False, False]])

In [32]:
e

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [37]:
e[mask]

array([0, 6])

In [38]:
mask = ((e%3 == 0)|(e%2==0))
mask

array([[ True, False,  True,  True],
       [ True, False,  True, False],
       [ True,  True,  True, False]])

In [41]:
e[mask]

array([ 0,  2,  3,  4,  6,  8,  9, 10])

In [42]:
e[mask]**2

array([  0,   4,   9,  16,  36,  64,  81, 100])

In [45]:
e[mask] = 21


In [46]:
e

array([[21,  1, 21, 21],
       [21,  5, 21,  7],
       [21, 21, 21, 11]])

In [48]:
a = np.arange(1,5)
a

array([1, 2, 3, 4])

In [62]:
b = np.arange(8,12)
b

array([ 8,  9, 10, 11])

In [63]:
c = a+b
c

array([ 9, 11, 13, 15])

In [64]:
a*b

array([ 8, 18, 30, 44])

In [65]:
a/b

array([0.125     , 0.22222222, 0.3       , 0.36363636])

In [66]:
a%b

array([1, 2, 3, 4])

In [68]:
a**b

array([      1,     512,   59049, 4194304])

In [58]:
b = np.arange(8,13)
b

array([ 8,  9, 10, 11, 12])

# Make a note of the error received when array size is different

In [59]:
c = a+b
c

ValueError: ignored

#Aggregate / Universal Functions on 1D array (ufunc)

In [69]:
arr=np.arange(1,31).reshape((6,5))
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [70]:
np.sum(arr,axis=0)

array([ 81,  87,  93,  99, 105])

In [71]:
np.sum(arr,axis=1)

array([ 15,  40,  65,  90, 115, 140])

In [72]:
np.max(arr,axis=0)

array([26, 27, 28, 29, 30])

In [74]:
np.max(arr,axis=1)

array([ 5, 10, 15, 20, 25, 30])

In [73]:
np.min(arr,axis=1)

array([ 1,  6, 11, 16, 21, 26])

In [75]:
np.min(arr,axis=0)

array([1, 2, 3, 4, 5])

In [76]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [78]:
np.zeros((3,3))+5

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [79]:
np.zeros((3,3))/5

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [82]:
np.ones((3,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [84]:
np.ones((3,3),dtype=np.uint32)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=uint32)

In [86]:
np.ones((3,3),dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [87]:
np.full((4,3),7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [88]:
np.full((4,3),7) **3

array([[343, 343, 343],
       [343, 343, 343],
       [343, 343, 343],
       [343, 343, 343]])

In [90]:
x = (np.full((4,3),7) ** 3)
x

array([[343, 343, 343],
       [343, 343, 343],
       [343, 343, 343],
       [343, 343, 343]])

In [91]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

###np.eye creates a desired matrix possible number of identity values

In [92]:
np.eye(10,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [99]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [101]:
np.diag([1,2,3,4,5],5)

array([[0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 3, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 4, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 5],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [104]:
(np.diag([1,2,3,4,5],5)+5)*3%2


array([[1, 1, 1, 1, 1, 0, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 0, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [106]:
np.diag([11,45,32])

array([[11,  0,  0],
       [ 0, 45,  0],
       [ 0,  0, 32]])

In [108]:
np.diag(np.arange(1,12))

array([[ 1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  2,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  3,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  4,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  5,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  6,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  7,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  8,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  9,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 10,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 11]])

In [109]:
m=np.array([1,2,3,4])
n=np.array([0,1,2,3])
m<n

array([False, False, False, False])

In [110]:
np.any(m<n)

False

In [111]:
m=np.array([1,1,3,4])
n=np.array([0,2,2,3])
m<n

array([False,  True, False, False])

In [112]:
np.any(m<n)

True

In [113]:
a

array([1, 2, 3, 4])

In [116]:
b = np.array([1,2,3,4])
b

array([1, 2, 3, 4])

In [117]:
a==b

array([ True,  True,  True,  True])

In [118]:
np.all(a==b)

True

In [119]:
a


array([1, 2, 3, 4])

In [120]:
b[1] = 212

In [121]:
b

array([  1, 212,   3,   4])

In [122]:
np.all(a==b)

False

###np.where will give the index of where the condition meets True and then we can pass them as list index for any n dimensional matrices

In [125]:
np.where(a==b)

(array([0, 2, 3]),)

In [126]:
a[np.where(a==b)]

array([1, 3, 4])