In [1]:
b = np.array([1,2,3,4,5])

NameError: ignored

In [5]:
import numpy as np
np.array?

b = np.array([1,2,3,4,5])
b


array([1, 2, 3, 4, 5])

In [5]:
type(b)

numpy.ndarray

In [6]:
b.ndim

1

In [7]:
b.shape

(5,)

In [10]:
a = [1,2,3,4,5]
b = %timeit [i**2 for i in a]
b

1.57 µs ± 255 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [11]:
a = np.array([1,2,3,4,5])

In [12]:
%timeit b = a**2

858 ns ± 10.1 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [13]:
type(a)

numpy.ndarray

In [15]:
a.dtype

dtype('int64')

In [33]:
for i in range(1,10,5):
  print (i)

1
6


In [26]:
for i in b:
  print(b,end=" ")

range(1, 10, 2) range(1, 10, 2) range(1, 10, 2) range(1, 10, 2) range(1, 10, 2) 

In [17]:
a = np.arange(0,34,2)
a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32])

In [24]:
for i in a:
  if (i%3==0) and (i%2==0) :
    print(i, end=" ")

0 6 12 18 24 30 

In [35]:
C

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32])

In [36]:
print(type(a))

<class 'numpy.ndarray'>


In [37]:
print(a.dtype)

int64


In [38]:
a = np.arange(0,34,2.5)
a

array([ 0. ,  2.5,  5. ,  7.5, 10. , 12.5, 15. , 17.5, 20. , 22.5, 25. ,
       27.5, 30. , 32.5])

In [39]:
print(type(a))

<class 'numpy.ndarray'>


In [40]:
print(a.dtype)

float64


In [42]:
a = np.array([1,2,3,4,5,6.7])
a

array([1. , 2. , 3. , 4. , 5. , 6.7])

In [43]:
print(a.dtype)

float64


In [44]:
a = np.array([1,2,3,4,5,6.7,"c"])
a

array(['1', '2', '3', '4', '5', '6.7', 'c'], dtype='<U32')

In [45]:
print(a.dtype)

<U32


In [50]:
a = np.array([1,2,3,4,5,6.7,"c",True])
a


array(['1', '2', '3', '4', '5', '6.7', 'c', 'True'], dtype='<U32')

In [48]:
a = np.array([1,2,3,4,5,6.7,True])
a

array([1. , 2. , 3. , 4. , 5. , 6.7, 1. ])

In [51]:
a = np.array([1,2,3,4,5,6.7,True,"c","gr"])
a

array(['1', '2', '3', '4', '5', '6.7', 'True', 'c', 'gr'], dtype='<U32')

In [52]:
a = np.array([True,False])
a

array([ True, False])

In [53]:
print(a.dtype)

bool


In [7]:
a = np.linspace(1,20,39)
a

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5, 11. , 11.5,
       12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. , 16.5, 17. ,
       17.5, 18. , 18.5, 19. , 19.5, 20. ])

In [3]:
a = np.linspace(0,100,5)
a

array([  0.,  25.,  50.,  75., 100.])

In [4]:
np.linspace?


### Working with 2D Matrices

---



In [57]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [58]:
a.ndim

2

In [9]:
a.shape

(3, 3)

In [10]:
type(a)

numpy.ndarray

In [66]:
a = np.arange(1,13)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [67]:
a.ndim

1

In [68]:
a.reshape((3,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [69]:
a.ndim

1

In [51]:
a.reshape((1,12))

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [18]:
# This will raise an error
a.reshape((-1,-1))

ValueError: ignored

In [19]:
a.reshape((-1,1))

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [55]:
a.reshape((2,6))

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [56]:
a.ndim

1

In [53]:
b = a.reshape((3,4))
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [54]:
b.ndim

2

In [27]:
b.shape

(3, 4)

In [24]:
c = b.T
c


array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [25]:
c.ndim

2

In [26]:
c.shape

(4, 3)

In [29]:
print(b==c)

False


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  """Entry point for launching an IPython kernel.


In [33]:
a


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [34]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [35]:
c

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [70]:
id(a)

139964202521392

In [72]:
id(b)

139964202769360

In [73]:
id(c)

139964202710576

In [74]:
c.flatten()

array([ 1,  5,  9,  2,  6, 10,  3,  7, 11,  4,  8, 12])

In [75]:
c.ndim

2

In [82]:
a = np.arange(1,13).reshape((4,3))
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [83]:
a.ndim

2

In [86]:
a[[0,1,3],::2]

array([[ 1,  3],
       [ 4,  6],
       [10, 12]])

In [99]:
a[[0,1,3],0:2]

array([[ 1,  2],
       [ 4,  5],
       [10, 11]])

In [100]:
a[(0,1,3),0:2]

array([[ 1,  2],
       [ 4,  5],
       [10, 11]])